auto: true

markdown: rdiscount

highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: “Hack Code”
title: Hack Code
description: Everything about hack&code.
url: http://m12redx.github.io
feed: /atom.xml
author_info: <a href="http://m12redx.github.io/">Hack Code</a>
